# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b44bec9c04cf880ee2b9861a95f20cfca27ed93a9526a5470c0d2c5af8122c1a4b6c3fe0ad6122578aa0f9e8b068fa67184f997229a98b5503ee41aca8ce62a9

test:
  secret_key_base: 5d41a92614066d315a02a273b36d2c14d5d6845a83ba4ee837f1741e6f25c5a7821ab19be08c010ef5db3d89e3ae1e8d95697866637da1ac237b231bbe47ec33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
